name: auto prettier
on: pull_request
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn --frozen-lockfile
      - run: yarn format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply auto prettier"
          commit_user_name: 俺
          commit_user_email: 俺@mizle.net
